### ISSUE TITLE
Intellij 2020.1.1 version is not supported

### ISSUE THREAD

**Issue by erdemy** [JetBrains/tfsIntegration#3]
Hi,
I got the following error in Intellij 2020.1.1:
Plugin Error: Plugin "TFS" is incompatible (until build 193.SNAPSHOT < IU-201.7223.91).

**Comment by dmitriysmirnovjb** [comment]
The plugin has reached end-of-support in 2020.1. Please see https://blog.jetbrains.com/idea/2020/01/end-of-support-for-tfs-2014-and-older/

You can build a compatible version using the source of this repository.

**Comment by erdemy** [comment]
Thanks @dmitriysmirnovjb 
built the plugin from the source, let me upload it if someone is needed:

[idea-tfs-201.zip](https://github.com/JetBrains/tfsIntegration/files/4681384/idea-tfs-201.zip)
(Load the jar using Settings/Preferences - Plugins)

regards,
