### ISSUE TITLE
Parameterizing variables issue under Version Control

### ISSUE THREAD

**Issue by smaamirhash** [JetBrains/tfsIntegration#5]
Hello,

We're trying to integrate a source code repository located on TFS GIT portal via a new CI build and by associating with a proper service account with appropriate Read/Write accesses in it. But noticed that, under Version Control Settings, if we specify a parameterized variable lets say "github_repo_location" at the end of the repository URL link, it returns with the following exceptions (Actual project names are hidden so just a simulation of the error):

_"Test connection failed in Project Area/Sub-Project Area/Template_Configurations/Docker_Build
List remote refs failed: cannot locate repository at http://tfs_server.com:8080/tfs/DefaultCollection/ProjectName%20ProjectName%20ProjectName%20Solution/_git/: http://tfs_server.com:8080/tfs/DefaultCollection/ProjectName%20ProjectName%20ProjectName%20Solution/_git/info/refs?service=git-upload-pack not found: Not Found_

Repo URL being used (As a sample w/o actual project names): 
http://tfs_server.com:8080/tfs/DefaultCollection/ProjectName%20ProjectName%20ProjectName%20Solution/_git/**%git-repo-location%**

Please note that in the above URL, there is a space in the repository names. Plus, we're using the parameterized variable (%git-repo-location%) whose value is already provided correctly under the parameter tab of its associated build configurations (for e.g: "refs/head/development" branch). But it's strange that during the runtime of the build, there's no impact or error thrown in the build logs as it looks like it is still able to poll up the latest SCM changes from that same TFS GIT repo properly. **But** when using the '**Test Connection**' button under Version Control Settings, it displays that above error, but why? Is it cuz there's a space in the repo name? If that's the case then the same way it used to work in the previous TC build versions which we had before. That error just confuses and gives us a false impression that the integration between TC and TFS GIT is still not properly configured.

Here's our build version details:

TeamCity Enterprise Edition: 2020.1.2 (build 78726)

Please let me know if you need any additional information or details around this.

Thanks again!

**Comment by smaamirhash** [comment]
Can someone from TC team please respond on this issue please?...

**Comment by dmitriysmirnovjb** [comment]
Hello smaamirhash,

Sorry, but this is not the right place to ask TeamCity related questions, because this is a plugin for Intellij in the first place, not related to TeamCity, and aslo this is an obsolete one.

Please consider contacting [Teamcity support](https://teamcity-support.jetbrains.com/hc/en-us/requests/new) or posting on the [TeamCity forums](https://teamcity-support.jetbrains.com/hc/en-us/community/topics/)

**Comment by smaamirhash** [comment]
Sure, thanks for this correction, appreciated.
